### ISSUE TITLE
stomp.py version changes

### ISSUE THREAD

**Issue by IgnoredAmbience** [openraildata/stomp-client-python#7]
As of stomp.py version 5, the `connection.start()` function has been removed. The [use of the function in this code](https://github.com/openraildata/stomp-client-python/blob/master/opendata-networkrail-client.py#L39) should either be removed, or a compatible major version of the stomp.py version specified.

**Comment by poggs** [comment]
Are you able to submit a PR?

**Comment by IgnoredAmbience** [comment]
Which approach would you prefer? I note there's no dependency versioning given in the repo at present, which leaves open the potential for similar regressions in future.

**Comment by poggs** [comment]
A PR which locks the dependency to the version that the code works with would be the simplest thing to start with - and a PR which uses the latest version with code changes, if you have time, please.  But unless there's anything fundamentally better or fixed in the version that deprecates the start() method, the former is a good use of everyone's time

**Comment by IgnoredAmbience** [comment]
Version 5 of the library removes python 2 support, which might be a step too far for some. PR just adds the version requirement to the `pip install` line, as I'm still unsure what the preferred python dependency solution is, and adding one to this repo is too much for me at present.
